import type {
  Store,
  Product,
  ScrapeJob,
  ProductChange,
  MonitoringLog,
  MonitoringConfig,
  AIGeneratedContent,
  Activity,
  DashboardStats,
  AIActivityLog,
} from "@/types";

// ─── Dashboard Stats ───

export const mockStats: DashboardStats = {
  total_products: 12847,
  active_stores: 8,
  total_jobs: 342,
  alerts_today: 23,
  ai_generated: 156,
};

// ─── Stores ───

export const mockStores: Store[] = [
  {
    id: "s1",
    user_id: "u1",
    url: "https://gymshark.com",
    name: "Gymshark",
    product_count: 2341,
    last_scraped_at: "2026-02-13T08:30:00Z",
    status: "active",
    created_at: "2026-01-15T10:00:00Z",
    platform: "shopify",
    affiliate_link_base: "https://go.gymshark.com",
    program_id: "GS-AFF-001",
    coupon_code: "DEAL15",
    is_published: true,
    is_featured: true,
    logo_url: "https://picsum.photos/seed/gs-logo/100/100",
    description_en: "Premium fitness apparel and accessories brand.",
    description_de: "Premium Fitnessbekleidung und Accessoires Marke.",
  },
  {
    id: "s2",
    user_id: "u1",
    url: "https://allbirds.com",
    name: "Allbirds",
    product_count: 187,
    last_scraped_at: "2026-02-13T07:45:00Z",
    status: "active",
    created_at: "2026-01-20T14:00:00Z",
    platform: "shopify",
    affiliate_link_base: "https://go.allbirds.com",
    program_id: "AB-AFF-002",
    coupon_code: null,
    is_published: true,
    is_featured: true,
    logo_url: "https://picsum.photos/seed/ab-logo/100/100",
    description_en: "Sustainable footwear made from natural materials.",
    description_de: "Nachhaltige Schuhe aus natürlichen Materialien.",
  },
  {
    id: "s3",
    user_id: "u1",
    url: "https://tentree.com",
    name: "Tentree",
    product_count: 534,
    last_scraped_at: "2026-02-12T22:00:00Z",
    status: "active",
    created_at: "2026-01-22T09:00:00Z",
    platform: "shopify",
    affiliate_link_base: "https://go.tentree.com",
    program_id: "TT-AFF-003",
    coupon_code: "EARTH10",
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/tt-logo/100/100",
    description_en: "Eco-friendly apparel that plants trees.",
    description_de: "Umweltfreundliche Kleidung, die Bäume pflanzt.",
  },
  {
    id: "s4",
    user_id: "u1",
    url: "https://chubbiesshorts.com",
    name: "Chubbies",
    product_count: 892,
    last_scraped_at: "2026-02-13T06:15:00Z",
    status: "active",
    created_at: "2026-01-25T16:00:00Z",
    platform: "shopify",
    affiliate_link_base: "https://go.chubbies.com",
    program_id: "CH-AFF-004",
    coupon_code: "WEEKEND20",
    is_published: true,
    is_featured: true,
    logo_url: "https://picsum.photos/seed/ch-logo/100/100",
    description_en: "Weekend-ready shorts and casual wear.",
    description_de: "Wochenend-Shorts und Freizeitkleidung.",
  },
  {
    id: "s5",
    user_id: "u1",
    url: "https://bombas.com",
    name: "Bombas",
    product_count: 423,
    last_scraped_at: "2026-02-10T12:00:00Z",
    status: "paused",
    created_at: "2026-01-28T11:00:00Z",
    platform: "shopify",
    affiliate_link_base: null,
    program_id: null,
    coupon_code: null,
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/bb-logo/100/100",
    description_en: "Comfort-focused socks and underwear.",
    description_de: "Komfortorientierte Socken und Unterwäsche.",
  },
  {
    id: "s6",
    user_id: "u1",
    url: "https://fashionnova.com",
    name: "Fashion Nova",
    product_count: 8470,
    last_scraped_at: null,
    status: "error",
    created_at: "2026-02-01T08:00:00Z",
    platform: "custom",
    affiliate_link_base: "https://go.fashionnova.com",
    program_id: "FN-AFF-006",
    coupon_code: "NOVA30",
    is_published: false,
    is_featured: false,
    logo_url: null,
    description_en: null,
    description_de: null,
  },
  {
    id: "s7",
    user_id: "u1",
    url: "https://kith.com",
    name: "Kith",
    product_count: 3120,
    last_scraped_at: "2026-02-13T05:00:00Z",
    status: "active",
    created_at: "2026-01-10T09:00:00Z",
    platform: "shopify",
    affiliate_link_base: "https://go.kith.com",
    program_id: "KT-AFF-007",
    coupon_code: null,
    is_published: true,
    is_featured: true,
    logo_url: "https://picsum.photos/seed/kt-logo/100/100",
    description_en: "Premium streetwear and sneaker culture.",
    description_de: "Premium Streetwear und Sneaker-Kultur.",
  },
  {
    id: "s8",
    user_id: "u1",
    url: "https://ssense.com",
    name: "SSENSE",
    product_count: 14500,
    last_scraped_at: "2026-02-12T16:00:00Z",
    status: "active",
    created_at: "2026-01-12T10:00:00Z",
    platform: "custom",
    affiliate_link_base: "https://go.ssense.com",
    program_id: "SS-AFF-008",
    coupon_code: null,
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/ss-logo/100/100",
    description_en: "Luxury and avant-garde designer fashion.",
    description_de: "Luxus und avantgardistische Designermode.",
  },
  {
    id: "s9",
    user_id: "u1",
    url: "https://endclothing.com",
    name: "END.",
    product_count: 9800,
    last_scraped_at: "2026-02-13T03:30:00Z",
    status: "active",
    created_at: "2026-01-14T11:00:00Z",
    platform: "magento",
    affiliate_link_base: "https://go.endclothing.com",
    program_id: "EN-AFF-009",
    coupon_code: "END15",
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/en-logo/100/100",
    description_en: "Premium menswear and streetwear retailer.",
    description_de: "Premium Herrenmode und Streetwear Händler.",
  },
  {
    id: "s10",
    user_id: "u1",
    url: "https://mrporter.com",
    name: "MR PORTER",
    product_count: 6200,
    last_scraped_at: "2026-02-11T20:00:00Z",
    status: "paused",
    created_at: "2026-01-16T13:00:00Z",
    platform: "custom",
    affiliate_link_base: "https://go.mrporter.com",
    program_id: "MP-AFF-010",
    coupon_code: null,
    is_published: false,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/mp-logo/100/100",
    description_en: "Luxury men's fashion from top designers.",
    description_de: "Luxus Herrenmode von Top-Designern.",
  },
  {
    id: "s11",
    user_id: "u1",
    url: "https://revolve.com",
    name: "Revolve",
    product_count: 11300,
    last_scraped_at: "2026-02-13T07:00:00Z",
    status: "active",
    created_at: "2026-01-18T08:00:00Z",
    platform: "custom",
    affiliate_link_base: "https://go.revolve.com",
    program_id: "RV-AFF-011",
    coupon_code: "REV10",
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/rv-logo/100/100",
    description_en: "Trend-driven fashion for young adults.",
    description_de: "Trendorientierte Mode für junge Erwachsene.",
  },
  {
    id: "s12",
    user_id: "u1",
    url: "https://farfetch.com",
    name: "Farfetch",
    product_count: 22000,
    last_scraped_at: "2026-02-12T14:00:00Z",
    status: "error",
    created_at: "2026-01-19T15:00:00Z",
    platform: "custom",
    affiliate_link_base: "https://go.farfetch.com",
    program_id: "FF-AFF-012",
    coupon_code: null,
    is_published: false,
    is_featured: false,
    logo_url: null,
    description_en: "Global luxury fashion marketplace.",
    description_de: null,
  },
  {
    id: "s13",
    user_id: "u1",
    url: "https://urbanoutfitters.com",
    name: "Urban Outfitters",
    product_count: 4500,
    last_scraped_at: "2026-02-13T09:00:00Z",
    status: "active",
    created_at: "2026-01-21T10:00:00Z",
    platform: "magento",
    affiliate_link_base: "https://go.urbanoutfitters.com",
    program_id: "UO-AFF-013",
    coupon_code: "URBAN15",
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/uo-logo/100/100",
    description_en: "Bohemian and vintage-inspired lifestyle brand.",
    description_de: "Bohème und Vintage-inspirierte Lifestyle-Marke.",
  },
  {
    id: "s14",
    user_id: "u1",
    url: "https://asos.com",
    name: "ASOS",
    product_count: 31000,
    last_scraped_at: "2026-02-13T04:15:00Z",
    status: "active",
    created_at: "2026-01-23T12:00:00Z",
    platform: "custom",
    affiliate_link_base: "https://go.asos.com",
    program_id: "AS-AFF-014",
    coupon_code: "ASOS20",
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/as-logo/100/100",
    description_en: "Online fashion for 20-somethings worldwide.",
    description_de: "Online-Mode für junge Erwachsene weltweit.",
  },
  {
    id: "s15",
    user_id: "u1",
    url: "https://everlane.com",
    name: "Everlane",
    product_count: 620,
    last_scraped_at: "2026-02-12T19:00:00Z",
    status: "active",
    created_at: "2026-01-26T14:00:00Z",
    platform: "shopify",
    affiliate_link_base: "https://go.everlane.com",
    program_id: "EV-AFF-015",
    coupon_code: null,
    is_published: true,
    is_featured: false,
    logo_url: "https://picsum.photos/seed/ev-logo/100/100",
    description_en: "Radical transparency in ethical fashion.",
    description_de: "Radikale Transparenz in ethischer Mode.",
  },
  {
    id: "s16",
    user_id: "u1",
    url: "https://outerknown.com",
    name: "Outerknown",
    product_count: 340,
    last_scraped_at: "2026-02-11T10:00:00Z",
    status: "active",
    created_at: "2026-01-29T09:00:00Z",
    platform: "shopify",
    affiliate_link_base: null,
    program_id: null,
    coupon_code: null,
    is_published: true,
    is_featured: false,
    logo_url: null,
    description_en: "Sustainable surf and outdoor apparel.",
    description_de: null,
  },
];

// ─── Products ───

export const mockProducts: Product[] = [
  {
    id: "p1",
    store_id: "s1",
    title: "Apex Seamless T-Shirt",
    handle: "apex-seamless-t-shirt",
    sku: "GS-APX-001",
    brand: "Gymshark",
    price: 35.0,
    original_price: 45.0,
    compare_at_price: 45.0,
    discount_percentage: 22,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://gymshark.com/products/apex-seamless-t-shirt",
    image_url: "https://picsum.photos/seed/gymshark-tee/400/400",
    description: "Lightweight seamless construction for unrestricted movement.",
    updated_at: "2026-02-13T08:30:00Z",
    is_published: true,
    is_featured: true,
    is_slider: true,
    ai_category: "Activewear",
    affiliate_link: "https://go.gymshark.com/apex-tee",
    description_en: "Premium seamless training tee.",
    description_de: "Premium nahtloses Trainingsshirt.",
  },
  {
    id: "p2",
    store_id: "s1",
    title: "Power Leggings",
    handle: "power-leggings",
    sku: "GS-PWR-042",
    brand: "Gymshark Women",
    price: 54.99,
    original_price: 54.99,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://gymshark.com/products/power-leggings",
    image_url: "https://picsum.photos/seed/gymshark-leg/400/400",
    description: "High-waisted squat-proof leggings with side pocket.",
    updated_at: "2026-02-13T08:30:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Activewear",
    affiliate_link: "https://go.gymshark.com/power-leg",
    description_en: null,
    description_de: null,
  },
  {
    id: "p3",
    store_id: "s2",
    title: "Tree Runner",
    handle: "tree-runner",
    sku: "AB-TR-010",
    brand: "Allbirds",
    price: 98.0,
    original_price: 98.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: false,
    stock_status: "out_of_stock",
    product_url: "https://allbirds.com/products/tree-runner",
    image_url: "https://picsum.photos/seed/allbirds-tree/400/400",
    description: "Lightweight and breezy shoes made from responsibly sourced eucalyptus tree fiber.",
    updated_at: "2026-02-13T07:45:00Z",
    is_published: true,
    is_featured: true,
    is_slider: true,
    ai_category: "Footwear",
    affiliate_link: "https://go.allbirds.com/tree-runner",
    description_en: "Sustainable running shoe from eucalyptus.",
    description_de: "Nachhaltiger Laufschuh aus Eukalyptus.",
  },
  {
    id: "p4",
    store_id: "s2",
    title: "Wool Runner Mizzle",
    handle: "wool-runner-mizzle",
    sku: "AB-WRM-007",
    brand: "Allbirds Wool",
    price: 125.0,
    original_price: 145.0,
    compare_at_price: 145.0,
    discount_percentage: 14,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://allbirds.com/products/wool-runner-mizzle",
    image_url: "https://picsum.photos/seed/allbirds-wool/400/400",
    description: "Water-repellent wool shoes for wet weather.",
    updated_at: "2026-02-13T07:45:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Footwear",
    affiliate_link: "https://go.allbirds.com/wool-mizzle",
    description_en: null,
    description_de: null,
  },
  {
    id: "p5",
    store_id: "s3",
    title: "Essential Hoodie",
    handle: "essential-hoodie",
    sku: "TT-EH-019",
    brand: "Tentree Earth",
    price: 78.0,
    original_price: 68.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://tentree.com/products/essential-hoodie",
    image_url: "https://picsum.photos/seed/tentree-hood/400/400",
    description: "Classic hoodie made from organic cotton and recycled polyester.",
    updated_at: "2026-02-12T22:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Outerwear",
    affiliate_link: "https://go.tentree.com/hoodie",
    description_en: "Organic cotton hoodie.",
    description_de: "Bio-Baumwoll-Hoodie.",
  },
  {
    id: "p6",
    store_id: "s4",
    title: "The Original Stretch 5.5\" Short",
    handle: "the-original-stretch-5-5-short",
    sku: "CH-OS-055",
    brand: "Chubbies Originals",
    price: 69.5,
    original_price: 69.5,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://chubbiesshorts.com/products/the-original-stretch-5-5-short",
    image_url: "https://picsum.photos/seed/chubbies-short/400/400",
    description: "The short that started it all. 4-way stretch for maximum comfort.",
    updated_at: "2026-02-13T06:15:00Z",
    is_published: true,
    is_featured: true,
    is_slider: false,
    ai_category: "Shorts",
    affiliate_link: "https://go.chubbies.com/original",
    description_en: null,
    description_de: null,
  },
  {
    id: "p7",
    store_id: "s5",
    title: "Merino Wool Calf Socks 4-Pack",
    handle: "merino-wool-calf-socks-4-pack",
    sku: "BB-MW-4PK",
    brand: "Bombas",
    price: 62.8,
    original_price: 78.0,
    compare_at_price: 78.0,
    discount_percentage: 19,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://bombas.com/products/merino-wool-calf-socks-4-pack",
    image_url: "https://picsum.photos/seed/bombas-socks/400/400",
    description: "Temperature-regulating merino wool blend. Honeycomb arch support.",
    updated_at: "2026-02-10T12:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Socks",
    affiliate_link: null,
    description_en: "Merino wool temperature-regulating socks.",
    description_de: "Temperaturausgleichende Merino-Socken.",
  },
  {
    id: "p8",
    store_id: "s6",
    title: "Nova Curve Jeans",
    handle: "nova-curve-jeans",
    sku: "FN-NCJ-301",
    brand: "Nova Curve",
    price: 32.99,
    original_price: 49.99,
    compare_at_price: 49.99,
    discount_percentage: 34,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://fashionnova.com/products/nova-curve-jeans",
    image_url: "https://picsum.photos/seed/fashionnova-jeans/400/400",
    description: "High-rise stretch denim with curve-hugging fit.",
    updated_at: "2026-02-01T08:00:00Z",
    is_published: false,
    is_featured: false,
    is_slider: false,
    ai_category: "Jeans",
    affiliate_link: "https://go.fashionnova.com/curve-jeans",
    description_en: null,
    description_de: null,
  },
  {
    id: "p9",
    store_id: "s1",
    title: "Vital Seamless 2.0 Sports Bra",
    handle: "vital-seamless-2-sports-bra",
    sku: "GS-VS2-088",
    brand: "Gymshark Vital",
    price: 30.0,
    original_price: 30.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://gymshark.com/products/vital-seamless-2-sports-bra",
    image_url: "https://picsum.photos/seed/gymshark-bra/400/400",
    description: "Seamless knit fabric with sweat-wicking technology.",
    updated_at: "2026-02-13T08:30:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Activewear",
    affiliate_link: "https://go.gymshark.com/vital-bra",
    description_en: null,
    description_de: null,
  },
  {
    id: "p10",
    store_id: "s1",
    title: "Rest Day Sweats Joggers",
    handle: "rest-day-sweats-joggers",
    sku: "GS-RDS-112",
    brand: "Gymshark",
    price: 44.0,
    original_price: 55.0,
    compare_at_price: 55.0,
    discount_percentage: 20,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://gymshark.com/products/rest-day-sweats-joggers",
    image_url: "https://picsum.photos/seed/gymshark-jogger/400/400",
    description: "Brushed fleece joggers built for recovery days.",
    updated_at: "2026-02-13T08:30:00Z",
    is_published: true,
    is_featured: false,
    is_slider: true,
    ai_category: "Activewear",
    affiliate_link: "https://go.gymshark.com/rest-day",
    description_en: "Comfy fleece joggers.",
    description_de: "Bequeme Fleece-Jogginghose.",
  },
  {
    id: "p11",
    store_id: "s2",
    title: "Tree Dasher 2",
    handle: "tree-dasher-2",
    sku: "AB-TD2-015",
    brand: "Allbirds",
    price: 135.0,
    original_price: 135.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://allbirds.com/products/tree-dasher-2",
    image_url: "https://picsum.photos/seed/allbirds-dasher/400/400",
    description: "Performance running shoe made from natural materials.",
    updated_at: "2026-02-13T07:45:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Footwear",
    affiliate_link: "https://go.allbirds.com/dasher-2",
    description_en: null,
    description_de: null,
  },
  {
    id: "p12",
    store_id: "s2",
    title: "Wool Piper",
    handle: "wool-piper",
    sku: "AB-WP-022",
    brand: "Allbirds Wool",
    price: 88.0,
    original_price: 110.0,
    compare_at_price: 110.0,
    discount_percentage: 20,
    currency: "USD",
    in_stock: false,
    stock_status: "out_of_stock",
    product_url: "https://allbirds.com/products/wool-piper",
    image_url: "https://picsum.photos/seed/allbirds-piper/400/400",
    description: "Casual slip-on sneaker in soft merino wool.",
    updated_at: "2026-02-12T18:00:00Z",
    is_published: false,
    is_featured: false,
    is_slider: false,
    ai_category: "Footwear",
    affiliate_link: null,
    description_en: null,
    description_de: null,
  },
  {
    id: "p13",
    store_id: "s3",
    title: "Juniper Classic T-Shirt",
    handle: "juniper-classic-t-shirt",
    sku: "TT-JC-033",
    brand: "Tentree",
    price: 42.0,
    original_price: 42.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://tentree.com/products/juniper-classic-t-shirt",
    image_url: "https://picsum.photos/seed/tentree-tee/400/400",
    description: "Organic cotton tee. 10 trees planted for every purchase.",
    updated_at: "2026-02-12T22:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Tops",
    affiliate_link: "https://go.tentree.com/juniper-tee",
    description_en: null,
    description_de: null,
  },
  {
    id: "p14",
    store_id: "s3",
    title: "Destination Jogger",
    handle: "destination-jogger",
    sku: "TT-DJ-041",
    brand: "Tentree",
    price: 62.0,
    original_price: 78.0,
    compare_at_price: 78.0,
    discount_percentage: 21,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://tentree.com/products/destination-jogger",
    image_url: "https://picsum.photos/seed/tentree-jogger/400/400",
    description: "French terry joggers with sustainable TENCEL blend.",
    updated_at: "2026-02-11T14:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Bottoms",
    affiliate_link: "https://go.tentree.com/dest-jogger",
    description_en: "Sustainable TENCEL joggers.",
    description_de: "Nachhaltige TENCEL-Jogginghose.",
  },
  {
    id: "p15",
    store_id: "s4",
    title: "The Weekend Breaker 7\" Short",
    handle: "weekend-breaker-7-short",
    sku: "CH-WB-070",
    brand: "Chubbies",
    price: 59.5,
    original_price: 59.5,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://chubbiesshorts.com/products/weekend-breaker-7-short",
    image_url: "https://picsum.photos/seed/chubbies-breaker/400/400",
    description: "Versatile 7-inch inseam short with mesh-lined pockets.",
    updated_at: "2026-02-13T06:15:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Shorts",
    affiliate_link: "https://go.chubbies.com/breaker",
    description_en: null,
    description_de: null,
  },
  {
    id: "p16",
    store_id: "s4",
    title: "The Drifter Hoodie",
    handle: "the-drifter-hoodie",
    sku: "CH-DH-085",
    brand: "Chubbies Outerwear",
    price: 74.0,
    original_price: 89.0,
    compare_at_price: 89.0,
    discount_percentage: 17,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://chubbiesshorts.com/products/the-drifter-hoodie",
    image_url: "https://picsum.photos/seed/chubbies-hoodie/400/400",
    description: "Lightweight fleece hoodie for post-beach layering.",
    updated_at: "2026-02-12T10:00:00Z",
    is_published: true,
    is_featured: true,
    is_slider: false,
    ai_category: "Outerwear",
    affiliate_link: "https://go.chubbies.com/drifter",
    description_en: "Lightweight post-beach hoodie.",
    description_de: "Leichter Strand-Hoodie.",
  },
  {
    id: "p17",
    store_id: "s5",
    title: "Gripper Ankle Socks 6-Pack",
    handle: "gripper-ankle-socks-6-pack",
    sku: "BB-GA-6PK",
    brand: "Bombas",
    price: 79.8,
    original_price: 79.8,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://bombas.com/products/gripper-ankle-socks-6-pack",
    image_url: "https://picsum.photos/seed/bombas-gripper/400/400",
    description: "Non-slip grip socks with blister tab protection.",
    updated_at: "2026-02-10T12:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Socks",
    affiliate_link: null,
    description_en: null,
    description_de: null,
  },
  {
    id: "p18",
    store_id: "s5",
    title: "Performance Running Crew Socks",
    handle: "performance-running-crew-socks",
    sku: "BB-PRC-009",
    brand: "Bombas Performance",
    price: 16.0,
    original_price: 20.0,
    compare_at_price: 20.0,
    discount_percentage: 20,
    currency: "USD",
    in_stock: false,
    stock_status: "out_of_stock",
    product_url: "https://bombas.com/products/performance-running-crew-socks",
    image_url: "https://picsum.photos/seed/bombas-running/400/400",
    description: "Moisture-wicking crew socks with targeted cushioning zones.",
    updated_at: "2026-02-09T08:00:00Z",
    is_published: false,
    is_featured: false,
    is_slider: false,
    ai_category: "Socks",
    affiliate_link: null,
    description_en: null,
    description_de: null,
  },
  {
    id: "p19",
    store_id: "s6",
    title: "Classic High Waist Skinny Jeans",
    handle: "classic-high-waist-skinny-jeans",
    sku: "FN-HWS-210",
    brand: "Nova Essentials",
    price: 27.99,
    original_price: 39.99,
    compare_at_price: 39.99,
    discount_percentage: 30,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://fashionnova.com/products/classic-high-waist-skinny-jeans",
    image_url: "https://picsum.photos/seed/fashionnova-skinny/400/400",
    description: "Figure-flattering high waist with super stretch fabric.",
    updated_at: "2026-02-06T18:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Jeans",
    affiliate_link: "https://go.fashionnova.com/hw-skinny",
    description_en: null,
    description_de: null,
  },
  {
    id: "p20",
    store_id: "s6",
    title: "Off Shoulder Ruched Mini Dress",
    handle: "off-shoulder-ruched-mini-dress",
    sku: "FN-OSD-415",
    brand: "NovaGirl",
    price: 34.99,
    original_price: 34.99,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://fashionnova.com/products/off-shoulder-ruched-mini-dress",
    image_url: "https://picsum.photos/seed/fashionnova-dress/400/400",
    description: "Bodycon mini dress with ruched detailing and off-shoulder neckline.",
    updated_at: "2026-02-03T18:00:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Dresses",
    affiliate_link: "https://go.fashionnova.com/ruched-dress",
    description_en: null,
    description_de: null,
  },
  {
    id: "p21",
    store_id: "s1",
    title: "Arrival 5\" Shorts",
    handle: "arrival-5-shorts",
    sku: "GS-ARR-055",
    brand: "GS Training",
    price: 28.0,
    original_price: 28.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://gymshark.com/products/arrival-5-shorts",
    image_url: "https://picsum.photos/seed/gymshark-shorts/400/400",
    description: "Lightweight training shorts with zip pocket.",
    updated_at: "2026-02-13T08:30:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Activewear",
    affiliate_link: "https://go.gymshark.com/arrival",
    description_en: null,
    description_de: null,
  },
  {
    id: "p22",
    store_id: "s1",
    title: "Crest Hoodie",
    handle: "crest-hoodie",
    sku: "GS-CRH-071",
    brand: "Gymshark",
    price: 48.0,
    original_price: 60.0,
    compare_at_price: 60.0,
    discount_percentage: 20,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://gymshark.com/products/crest-hoodie",
    image_url: "https://picsum.photos/seed/gymshark-crest/400/400",
    description: "Oversized pullover hoodie with embroidered crest logo.",
    updated_at: "2026-02-12T08:30:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Outerwear",
    affiliate_link: "https://go.gymshark.com/crest",
    description_en: "Oversized hoodie with crest logo.",
    description_de: "Übergroßer Hoodie mit Wappen-Logo.",
  },
  {
    id: "p23",
    store_id: "s4",
    title: "The Swim Trunk 5.5\"",
    handle: "the-swim-trunk-5-5",
    sku: "CH-ST-055",
    brand: "Chubbies Swim",
    price: 64.0,
    original_price: 64.0,
    compare_at_price: null,
    discount_percentage: 0,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://chubbiesshorts.com/products/the-swim-trunk-5-5",
    image_url: "https://picsum.photos/seed/chubbies-swim/400/400",
    description: "Quick-dry swim trunks with compression liner.",
    updated_at: "2026-02-13T06:15:00Z",
    is_published: true,
    is_featured: false,
    is_slider: false,
    ai_category: "Swimwear",
    affiliate_link: "https://go.chubbies.com/swim-trunk",
    description_en: null,
    description_de: null,
  },
  {
    id: "p24",
    store_id: "s6",
    title: "Oversized Graphic Tee",
    handle: "oversized-graphic-tee",
    sku: "FN-OGT-520",
    brand: "NovaMEN",
    price: 18.99,
    original_price: 24.99,
    compare_at_price: 24.99,
    discount_percentage: 24,
    currency: "USD",
    in_stock: true,
    stock_status: "in_stock",
    product_url: "https://fashionnova.com/products/oversized-graphic-tee",
    image_url: "https://picsum.photos/seed/fashionnova-graphic/400/400",
    description: "Relaxed fit graphic tee with vintage wash.",
    updated_at: "2026-02-03T18:00:00Z",
    is_published: false,
    is_featured: false,
    is_slider: false,
    ai_category: "Tops",
    affiliate_link: "https://go.fashionnova.com/graphic-tee",
    description_en: null,
    description_de: null,
  },
];

// ─── Scrape Jobs ───

export const mockScrapeJobs: ScrapeJob[] = [
  {
    id: "j1",
    store_id: "s1",
    store_name: "Gymshark",
    status: "completed",
    products_found: 2341,
    products_updated: 18,
    started_at: "2026-02-13T08:20:00Z",
    completed_at: "2026-02-13T08:30:00Z",
    error_message: null,
  },
  {
    id: "j2",
    store_id: "s2",
    store_name: "Allbirds",
    status: "completed",
    products_found: 187,
    products_updated: 3,
    started_at: "2026-02-13T07:40:00Z",
    completed_at: "2026-02-13T07:45:00Z",
    error_message: null,
  },
  {
    id: "j3",
    store_id: "s4",
    store_name: "Chubbies",
    status: "completed",
    products_found: 892,
    products_updated: 3,
    started_at: "2026-02-13T06:05:00Z",
    completed_at: "2026-02-13T06:15:00Z",
    error_message: null,
  },
  {
    id: "j4",
    store_id: "s3",
    store_name: "Tentree",
    status: "running",
    products_found: 0,
    products_updated: 0,
    started_at: "2026-02-13T09:10:00Z",
    completed_at: null,
    error_message: null,
  },
  {
    id: "j5",
    store_id: "s6",
    store_name: "Fashion Nova",
    status: "failed",
    products_found: 0,
    products_updated: 0,
    started_at: "2026-02-12T20:00:00Z",
    completed_at: "2026-02-12T20:02:00Z",
    error_message: "Connection timeout: store returned 503 after 30s",
  },
  {
    id: "j6",
    store_id: "s1",
    store_name: "Gymshark",
    status: "completed",
    products_found: 2338,
    products_updated: 42,
    started_at: "2026-02-12T08:20:00Z",
    completed_at: "2026-02-12T08:31:00Z",
    error_message: null,
  },
  {
    id: "j7",
    store_id: "s5",
    store_name: "Bombas",
    status: "completed",
    products_found: 423,
    products_updated: 7,
    started_at: "2026-02-10T11:50:00Z",
    completed_at: "2026-02-10T12:00:00Z",
    error_message: null,
  },
  {
    id: "j8",
    store_id: "s6",
    store_name: "Fashion Nova",
    status: "failed",
    products_found: 0,
    products_updated: 0,
    started_at: "2026-02-10T18:00:00Z",
    completed_at: "2026-02-10T18:01:30Z",
    error_message: "Rate limited by store (429). Retry after 3600s.",
  },
  {
    id: "j9",
    store_id: "s2",
    store_name: "Allbirds",
    status: "completed",
    products_found: 185,
    products_updated: 5,
    started_at: "2026-02-09T07:30:00Z",
    completed_at: "2026-02-09T07:36:00Z",
    error_message: null,
  },
  {
    id: "j10",
    store_id: "s1",
    store_name: "Gymshark",
    status: "completed",
    products_found: 2335,
    products_updated: 27,
    started_at: "2026-02-09T08:20:00Z",
    completed_at: "2026-02-09T08:32:00Z",
    error_message: null,
  },
  {
    id: "j11",
    store_id: "s4",
    store_name: "Chubbies",
    status: "completed",
    products_found: 890,
    products_updated: 11,
    started_at: "2026-02-09T06:00:00Z",
    completed_at: "2026-02-09T06:09:00Z",
    error_message: null,
  },
  {
    id: "j12",
    store_id: "s3",
    store_name: "Tentree",
    status: "completed",
    products_found: 412,
    products_updated: 2,
    started_at: "2026-02-08T14:00:00Z",
    completed_at: "2026-02-08T14:07:00Z",
    error_message: null,
  },
  {
    id: "j13",
    store_id: "s5",
    store_name: "Bombas",
    status: "completed",
    products_found: 420,
    products_updated: 0,
    started_at: "2026-02-08T11:50:00Z",
    completed_at: "2026-02-08T11:58:00Z",
    error_message: null,
  },
  {
    id: "j14",
    store_id: "s6",
    store_name: "Fashion Nova",
    status: "failed",
    products_found: 0,
    products_updated: 0,
    started_at: "2026-02-08T18:00:00Z",
    completed_at: "2026-02-08T18:00:45Z",
    error_message: "SSL handshake failed: CERT_HAS_EXPIRED",
  },
  {
    id: "j15",
    store_id: "s1",
    store_name: "Gymshark",
    status: "completed",
    products_found: 2330,
    products_updated: 65,
    started_at: "2026-02-07T08:20:00Z",
    completed_at: "2026-02-07T08:29:00Z",
    error_message: null,
  },
  {
    id: "j16",
    store_id: "s2",
    store_name: "Allbirds",
    status: "completed",
    products_found: 184,
    products_updated: 12,
    started_at: "2026-02-07T07:30:00Z",
    completed_at: "2026-02-07T07:35:00Z",
    error_message: null,
  },
  {
    id: "j17",
    store_id: "s4",
    store_name: "Chubbies",
    status: "completed",
    products_found: 888,
    products_updated: 6,
    started_at: "2026-02-07T06:05:00Z",
    completed_at: "2026-02-07T06:14:00Z",
    error_message: null,
  },
  {
    id: "j18",
    store_id: "s3",
    store_name: "Tentree",
    status: "completed",
    products_found: 410,
    products_updated: 8,
    started_at: "2026-02-06T14:00:00Z",
    completed_at: "2026-02-06T14:06:00Z",
    error_message: null,
  },
  {
    id: "j19",
    store_id: "s5",
    store_name: "Bombas",
    status: "failed",
    products_found: 0,
    products_updated: 0,
    started_at: "2026-02-06T11:50:00Z",
    completed_at: "2026-02-06T11:51:00Z",
    error_message: "Unexpected HTML structure: product grid not found",
  },
  {
    id: "j20",
    store_id: "s6",
    store_name: "Fashion Nova",
    status: "completed",
    products_found: 3720,
    products_updated: 94,
    started_at: "2026-02-06T18:00:00Z",
    completed_at: "2026-02-06T18:22:00Z",
    error_message: null,
  },
  {
    id: "j21",
    store_id: "s1",
    store_name: "Gymshark",
    status: "completed",
    products_found: 2328,
    products_updated: 31,
    started_at: "2026-02-05T08:20:00Z",
    completed_at: "2026-02-05T08:30:00Z",
    error_message: null,
  },
  {
    id: "j22",
    store_id: "s2",
    store_name: "Allbirds",
    status: "completed",
    products_found: 182,
    products_updated: 1,
    started_at: "2026-02-05T07:30:00Z",
    completed_at: "2026-02-05T07:34:00Z",
    error_message: null,
  },
  {
    id: "j23",
    store_id: "s4",
    store_name: "Chubbies",
    status: "completed",
    products_found: 885,
    products_updated: 14,
    started_at: "2026-02-05T06:05:00Z",
    completed_at: "2026-02-05T06:16:00Z",
    error_message: null,
  },
  {
    id: "j24",
    store_id: "s3",
    store_name: "Tentree",
    status: "failed",
    products_found: 0,
    products_updated: 0,
    started_at: "2026-02-04T14:00:00Z",
    completed_at: "2026-02-04T14:03:00Z",
    error_message: "DNS resolution failed for tentree.myshopify.com",
  },
  {
    id: "j25",
    store_id: "s5",
    store_name: "Bombas",
    status: "completed",
    products_found: 418,
    products_updated: 3,
    started_at: "2026-02-04T11:50:00Z",
    completed_at: "2026-02-04T11:59:00Z",
    error_message: null,
  },
  {
    id: "j26",
    store_id: "s1",
    store_name: "Gymshark",
    status: "completed",
    products_found: 2320,
    products_updated: 48,
    started_at: "2026-02-03T08:20:00Z",
    completed_at: "2026-02-03T08:31:00Z",
    error_message: null,
  },
  {
    id: "j27",
    store_id: "s6",
    store_name: "Fashion Nova",
    status: "completed",
    products_found: 3715,
    products_updated: 112,
    started_at: "2026-02-03T18:00:00Z",
    completed_at: "2026-02-03T18:25:00Z",
    error_message: null,
  },
  {
    id: "j28",
    store_id: "s2",
    store_name: "Allbirds",
    status: "completed",
    products_found: 180,
    products_updated: 9,
    started_at: "2026-02-02T07:30:00Z",
    completed_at: "2026-02-02T07:35:00Z",
    error_message: null,
  },
];

// ─── Product Changes ───

export const mockProductChanges: ProductChange[] = [
  {
    id: "pc1",
    product_id: "p1",
    store_id: "s1",
    store_name: "Gymshark",
    product_title: "Apex Seamless T-Shirt",
    product_image: "https://picsum.photos/seed/gymshark-tee/400/400",
    change_type: "price_change",
    field_changed: "price",
    old_value: "45.00",
    new_value: "35.00",
    detected_at: "2026-02-13T08:30:00Z",
  },
  {
    id: "pc2",
    product_id: "p3",
    store_id: "s2",
    store_name: "Allbirds",
    product_title: "Tree Runner",
    product_image: "https://picsum.photos/seed/allbirds-tree/400/400",
    change_type: "stock_change",
    field_changed: "in_stock",
    old_value: "true",
    new_value: "false",
    detected_at: "2026-02-13T07:45:00Z",
  },
  {
    id: "pc3",
    product_id: "p5",
    store_id: "s3",
    store_name: "Tentree",
    product_title: "Essential Hoodie",
    product_image: "https://picsum.photos/seed/tentree-hood/400/400",
    change_type: "price_change",
    field_changed: "price",
    old_value: "68.00",
    new_value: "78.00",
    detected_at: "2026-02-12T22:00:00Z",
  },
  {
    id: "pc4",
    product_id: "p4",
    store_id: "s2",
    store_name: "Allbirds",
    product_title: "Wool Runner Mizzle",
    product_image: "https://picsum.photos/seed/allbirds-wool/400/400",
    change_type: "price_change",
    field_changed: "price",
    old_value: "145.00",
    new_value: "125.00",
    detected_at: "2026-02-12T18:00:00Z",
  },
  {
    id: "pc5",
    product_id: "p6",
    store_id: "s4",
    store_name: "Chubbies",
    product_title: "The Original Stretch 5.5\" Short",
    product_image: "https://picsum.photos/seed/chubbies-short/400/400",
    change_type: "stock_change",
    field_changed: "stock_status",
    old_value: "in_stock",
    new_value: "out_of_stock",
    detected_at: "2026-02-13T06:15:00Z",
  },
  {
    id: "pc6",
    product_id: "p7",
    store_id: "s5",
    store_name: "Bombas",
    product_title: "Merino Wool Calf Socks 4-Pack",
    product_image: "https://picsum.photos/seed/bombas-socks/400/400",
    change_type: "price_change",
    field_changed: "price",
    old_value: "78.00",
    new_value: "62.80",
    detected_at: "2026-02-10T12:00:00Z",
  },
  {
    id: "pc7",
    product_id: "p8",
    store_id: "s1",
    store_name: "Gymshark",
    product_title: "Power Leggings",
    product_image: "https://picsum.photos/seed/gymshark-leg/400/400",
    change_type: "new_product",
    field_changed: "product",
    old_value: null,
    new_value: "added",
    detected_at: "2026-02-13T08:25:00Z",
  },
  {
    id: "pc8",
    product_id: "p9",
    store_id: "s6",
    store_name: "Fashion Nova",
    product_title: "Classic High Waist Skinny Jeans",
    product_image: "https://picsum.photos/seed/fashionnova-jean/400/400",
    change_type: "product_removed",
    field_changed: "product",
    old_value: "active",
    new_value: null,
    detected_at: "2026-02-12T20:00:00Z",
  },
  {
    id: "pc9",
    product_id: "p2",
    store_id: "s1",
    store_name: "Gymshark",
    product_title: "Apex Seamless T-Shirt",
    product_image: "https://picsum.photos/seed/gymshark-tee/400/400",
    change_type: "price_change",
    field_changed: "price",
    old_value: "50.00",
    new_value: "45.00",
    detected_at: "2026-02-11T14:00:00Z",
  },
  {
    id: "pc10",
    product_id: "p10",
    store_id: "s4",
    store_name: "Chubbies",
    product_title: "The Tahoe Fleece Pullover",
    product_image: "https://picsum.photos/seed/chubbies-fleece/400/400",
    change_type: "new_product",
    field_changed: "product",
    old_value: null,
    new_value: "added",
    detected_at: "2026-02-13T06:10:00Z",
  },
  {
    id: "pc11",
    product_id: "p3",
    store_id: "s2",
    store_name: "Allbirds",
    product_title: "Tree Runner",
    product_image: "https://picsum.photos/seed/allbirds-tree/400/400",
    change_type: "price_change",
    field_changed: "price",
    old_value: "98.00",
    new_value: "84.00",
    detected_at: "2026-02-11T09:30:00Z",
  },
  {
    id: "pc12",
    product_id: "p5",
    store_id: "s3",
    store_name: "Tentree",
    product_title: "Essential Hoodie",
    product_image: "https://picsum.photos/seed/tentree-hood/400/400",
    change_type: "stock_change",
    field_changed: "in_stock",
    old_value: "false",
    new_value: "true",
    detected_at: "2026-02-13T10:00:00Z",
  },
];

// ─── Monitoring Logs ───

export const mockMonitoringLogs: MonitoringLog[] = [
  {
    id: "ml1",
    store_id: "s1",
    store_name: "Gymshark",
    check_type: "full",
    status: "completed",
    changes_detected: 18,
    started_at: "2026-02-13T08:20:00Z",
    completed_at: "2026-02-13T08:30:00Z",
    error_message: null,
  },
  {
    id: "ml2",
    store_id: "s2",
    store_name: "Allbirds",
    check_type: "price_only",
    status: "completed",
    changes_detected: 2,
    started_at: "2026-02-13T07:40:00Z",
    completed_at: "2026-02-13T07:45:00Z",
    error_message: null,
  },
  {
    id: "ml3",
    store_id: "s3",
    store_name: "Tentree",
    check_type: "full",
    status: "running",
    changes_detected: 0,
    started_at: "2026-02-13T09:10:00Z",
    completed_at: null,
    error_message: null,
  },
  {
    id: "ml4",
    store_id: "s6",
    store_name: "Fashion Nova",
    check_type: "stock_only",
    status: "failed",
    changes_detected: 0,
    started_at: "2026-02-12T20:00:00Z",
    completed_at: "2026-02-12T20:02:00Z",
    error_message: "Connection timeout: store returned 503",
  },
  {
    id: "ml5",
    store_id: "s4",
    store_name: "Chubbies",
    check_type: "full",
    status: "completed",
    changes_detected: 3,
    started_at: "2026-02-13T06:05:00Z",
    completed_at: "2026-02-13T06:15:00Z",
    error_message: null,
  },
];

// ─── Monitoring Config ───

export const mockMonitoringConfigs: MonitoringConfig[] = [
  {
    id: "mc1",
    store_id: "s1",
    store_name: "Gymshark",
    check_interval_hours: 6,
    enabled: true,
    last_check_at: "2026-02-13T08:30:00Z",
    next_check_at: "2026-02-13T14:30:00Z",
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "mc2",
    store_id: "s2",
    store_name: "Allbirds",
    check_interval_hours: 12,
    enabled: true,
    last_check_at: "2026-02-13T07:45:00Z",
    next_check_at: "2026-02-13T19:45:00Z",
    created_at: "2026-01-20T14:00:00Z",
  },
  {
    id: "mc3",
    store_id: "s3",
    store_name: "Tentree",
    check_interval_hours: 24,
    enabled: true,
    last_check_at: "2026-02-12T22:00:00Z",
    next_check_at: "2026-02-13T22:00:00Z",
    created_at: "2026-01-22T09:00:00Z",
  },
  {
    id: "mc4",
    store_id: "s4",
    store_name: "Chubbies",
    check_interval_hours: 6,
    enabled: true,
    last_check_at: "2026-02-13T06:15:00Z",
    next_check_at: "2026-02-13T12:15:00Z",
    created_at: "2026-01-25T16:00:00Z",
  },
  {
    id: "mc5",
    store_id: "s5",
    store_name: "Bombas",
    check_interval_hours: 24,
    enabled: false,
    last_check_at: "2026-02-10T12:00:00Z",
    next_check_at: null,
    created_at: "2026-01-28T11:00:00Z",
  },
  {
    id: "mc6",
    store_id: "s6",
    store_name: "Fashion Nova",
    check_interval_hours: 12,
    enabled: true,
    last_check_at: null,
    next_check_at: null,
    created_at: "2026-02-01T08:00:00Z",
  },
];

// ─── AI Generated Content ───

export const mockAIContent: AIGeneratedContent[] = [
  {
    id: "ai1",
    store_id: "s1",
    store_name: "Gymshark",
    product_id: "p1",
    product_title: "Apex Seamless T-Shirt",
    content_type: "deal_post",
    content: "DEAL ALERT: Gymshark Apex Seamless T-Shirt just dropped 22% from $45 to $35! Lightweight seamless construction built for unrestricted movement. Grab it before it's gone.",
    created_at: "2026-02-13T08:35:00Z",
  },
  {
    id: "ai2",
    store_id: "s2",
    store_name: "Allbirds",
    product_id: "p4",
    product_title: "Wool Runner Mizzle",
    content_type: "deal_post",
    content: "Allbirds Wool Runner Mizzle now $125 (was $145) — 14% off! Water-repellent wool shoes perfect for rainy days. Sustainable comfort meets wet weather protection.",
    created_at: "2026-02-12T18:15:00Z",
  },
  {
    id: "ai3",
    store_id: "s5",
    store_name: "Bombas",
    product_id: "p7",
    product_title: "Merino Wool Calf Socks 4-Pack",
    content_type: "social_post",
    content: "Bombas Merino Wool Calf Socks 4-Pack marked down 19% to $62.80. Temperature-regulating wool blend with honeycomb arch support. Stock up while the sale lasts.",
    created_at: "2026-02-10T12:10:00Z",
  },
  {
    id: "ai4",
    store_id: "s4",
    store_name: "Chubbies",
    product_id: "p6",
    product_title: "The Original Stretch 5.5\" Short",
    content_type: "product_description",
    content: "The short that launched a movement. Chubbies' Original Stretch 5.5\" Short combines 4-way stretch fabric with a tailored fit that goes from beach to bar. Currently running low on stock — act fast.",
    created_at: "2026-02-13T06:20:00Z",
  },
  {
    id: "ai5",
    store_id: "s1",
    store_name: "Gymshark",
    product_id: null,
    product_title: null,
    content_type: "comparison",
    content: "Gymshark vs Allbirds — Q1 2026 Price Trends: Gymshark averaging 15% discounts across activewear, while Allbirds holds firm on footwear with selective 10-14% markdowns on last season styles.",
    created_at: "2026-02-11T14:00:00Z",
  },
];

// ─── Activity Feed ───

export const mockActivity: Activity[] = [
  {
    id: "a1",
    type: "price_change",
    title: "Price Drop Detected",
    description: "Apex Seamless T-Shirt dropped from $45 to $35",
    store_name: "Gymshark",
    timestamp: "2026-02-13T09:12:00Z",
  },
  {
    id: "a2",
    type: "ai_content_generated",
    title: "AI Deal Post Created",
    description: "Generated deal alert for Apex Seamless T-Shirt (22% off)",
    store_name: "Gymshark",
    timestamp: "2026-02-13T08:35:00Z",
  },
  {
    id: "a3",
    type: "stock_change",
    title: "Out of Stock",
    description: "Tree Runner in Charcoal (Size 10) now out of stock",
    store_name: "Allbirds",
    timestamp: "2026-02-13T08:30:00Z",
  },
  {
    id: "a4",
    type: "scrape_complete",
    title: "Scrape Complete",
    description: "Full catalog scraped — 892 products, 3 changes detected",
    store_name: "Chubbies",
    timestamp: "2026-02-13T06:15:00Z",
  },
  {
    id: "a5",
    type: "monitoring_alert",
    title: "Low Stock Alert",
    description: "Original Stretch 5.5\" Short running low on stock",
    store_name: "Chubbies",
    timestamp: "2026-02-13T06:16:00Z",
  },
  {
    id: "a6",
    type: "price_change",
    title: "Price Increase",
    description: "Essential Hoodie increased from $68 to $78",
    store_name: "Tentree",
    timestamp: "2026-02-12T22:10:00Z",
  },
  {
    id: "a7",
    type: "stock_change",
    title: "Back in Stock",
    description: "Wool Runner Mizzle restocked in all sizes",
    store_name: "Allbirds",
    timestamp: "2026-02-12T18:00:00Z",
  },
  {
    id: "a8",
    type: "store_added",
    title: "Store Added",
    description: "Fashion Nova added to monitoring",
    store_name: "Fashion Nova",
    timestamp: "2026-02-12T14:00:00Z",
  },
  {
    id: "a9",
    type: "new_product",
    title: "New Products Found",
    description: "3 new sock bundles added to catalog",
    store_name: "Bombas",
    timestamp: "2026-02-12T10:30:00Z",
  },
  {
    id: "a10",
    type: "ai_content_generated",
    title: "AI Comparison Generated",
    description: "Created Gymshark vs Allbirds Q1 price trend analysis",
    store_name: "Gymshark",
    timestamp: "2026-02-11T14:00:00Z",
  },
];

// ─── AI Activity Logs (Admin) ───

export const mockAIActivityLogs: AIActivityLog[] = [
  {
    id: "aal1",
    store_id: "s1",
    store_name: "Gymshark",
    product_id: "p1",
    product_title: "Apex Seamless T-Shirt",
    status: "success",
    scope: "descriptions",
    message: "Generated EN/DE descriptions for product",
    items_processed: 1,
    items_updated: 1,
    items_skipped: 0,
    created_at: "2026-02-13T10:30:00Z",
  },
  {
    id: "aal2",
    store_id: "s1",
    store_name: "Gymshark",
    product_id: null,
    product_title: null,
    status: "success",
    scope: "categories",
    message: "Categorized 42 uncategorized products",
    items_processed: 42,
    items_updated: 38,
    items_skipped: 4,
    created_at: "2026-02-13T09:15:00Z",
  },
  {
    id: "aal3",
    store_id: "s2",
    store_name: "Allbirds",
    product_id: "p3",
    product_title: "Tree Runner",
    status: "success",
    scope: "descriptions",
    message: "Generated EN/DE descriptions for product",
    items_processed: 1,
    items_updated: 1,
    items_skipped: 0,
    created_at: "2026-02-13T08:45:00Z",
  },
  {
    id: "aal4",
    store_id: "s6",
    store_name: "Fashion Nova",
    product_id: null,
    product_title: null,
    status: "error",
    scope: "full",
    message: "Store connection failed — could not fetch product data",
    items_processed: 0,
    items_updated: 0,
    items_skipped: 0,
    created_at: "2026-02-13T08:00:00Z",
  },
  {
    id: "aal5",
    store_id: "s4",
    store_name: "Chubbies",
    product_id: null,
    product_title: null,
    status: "success",
    scope: "descriptions",
    message: "Batch description generation for all products",
    items_processed: 892,
    items_updated: 645,
    items_skipped: 247,
    created_at: "2026-02-12T22:30:00Z",
  },
  {
    id: "aal6",
    store_id: "s3",
    store_name: "Tentree",
    product_id: "p5",
    product_title: "Essential Hoodie",
    status: "skipped",
    scope: "descriptions",
    message: "Product already has both EN and DE descriptions",
    items_processed: 1,
    items_updated: 0,
    items_skipped: 1,
    created_at: "2026-02-12T20:00:00Z",
  },
  {
    id: "aal7",
    store_id: "s2",
    store_name: "Allbirds",
    product_id: null,
    product_title: null,
    status: "success",
    scope: "categories",
    message: "Re-categorized 12 products with updated AI model",
    items_processed: 187,
    items_updated: 12,
    items_skipped: 175,
    created_at: "2026-02-12T16:00:00Z",
  },
  {
    id: "aal8",
    store_id: "s5",
    store_name: "Bombas",
    product_id: null,
    product_title: null,
    status: "success",
    scope: "full",
    message: "Full data clean completed — descriptions + categories",
    items_processed: 423,
    items_updated: 312,
    items_skipped: 111,
    created_at: "2026-02-12T14:00:00Z",
  },
  {
    id: "aal9",
    store_id: "s1",
    store_name: "Gymshark",
    product_id: "p10",
    product_title: "Rest Day Sweats Joggers",
    status: "success",
    scope: "descriptions",
    message: "Generated EN/DE descriptions for product",
    items_processed: 1,
    items_updated: 1,
    items_skipped: 0,
    created_at: "2026-02-12T11:00:00Z",
  },
  {
    id: "aal10",
    store_id: "s4",
    store_name: "Chubbies",
    product_id: "p6",
    product_title: "The Original Stretch 5.5\" Short",
    status: "skipped",
    scope: "categories",
    message: "Product already categorized as Shorts",
    items_processed: 1,
    items_updated: 0,
    items_skipped: 1,
    created_at: "2026-02-12T09:30:00Z",
  },
  {
    id: "aal11",
    store_id: "s6",
    store_name: "Fashion Nova",
    product_id: null,
    product_title: null,
    status: "error",
    scope: "descriptions",
    message: "Rate limit exceeded — retry after 60 minutes",
    items_processed: 15,
    items_updated: 8,
    items_skipped: 0,
    created_at: "2026-02-11T18:00:00Z",
  },
  {
    id: "aal12",
    store_id: "s3",
    store_name: "Tentree",
    product_id: null,
    product_title: null,
    status: "success",
    scope: "full",
    message: "Full data clean completed — descriptions + categories",
    items_processed: 534,
    items_updated: 421,
    items_skipped: 113,
    created_at: "2026-02-11T14:00:00Z",
  },
  {
    id: "aal13",
    store_id: "s1",
    store_name: "Gymshark",
    product_id: null,
    product_title: null,
    status: "success",
    scope: "descriptions",
    message: "Batch description generation for new products",
    items_processed: 18,
    items_updated: 16,
    items_skipped: 2,
    created_at: "2026-02-11T10:00:00Z",
  },
  {
    id: "aal14",
    store_id: "s2",
    store_name: "Allbirds",
    product_id: "p12",
    product_title: "Wool Piper",
    status: "success",
    scope: "descriptions",
    message: "Generated EN/DE descriptions for product",
    items_processed: 1,
    items_updated: 1,
    items_skipped: 0,
    created_at: "2026-02-10T22:00:00Z",
  },
  {
    id: "aal15",
    store_id: "s5",
    store_name: "Bombas",
    product_id: "p7",
    product_title: "Merino Wool Calf Socks 4-Pack",
    status: "skipped",
    scope: "categories",
    message: "Product already categorized as Socks",
    items_processed: 1,
    items_updated: 0,
    items_skipped: 1,
    created_at: "2026-02-10T18:00:00Z",
  },
];
